#v4:
#  - same as v3 but
#  - we can define per package options which are passed to derivation via 
#    variables


maintainers = [ "Eelco Dolstra <edolstra@gmail.com>" ]
description = "A description of a flake"

[config]
binary-caches = [ "https://my-cache.example.org" ]

[inputs]
nixpkgs = "20.03"
dwarffs = "master"

[[package]]
options =
  { who =
      { description = "Who we're saying hello to."
      , type = "string"
      , default = "World"
      }
  }
version = "1.2.0"
src = "./."
platforms = [ "x86_64-linux" "aarch64-macos" ]
dependencies = [
  "nixpkgs#cowsay",
  "nixpkgs#bash",
  "dwarffs",
]
buildPhase = """
  echo "Building hello.sh ..."
  cat > hello <<EOF
  #!$(realpath bash)
  exec $(realpath cowsay) Hello $OPTIONS_WHO
  EOF
  chmod +x hello
"""
installPhase = """
  mkdir -p $out/bin
  cp ./hello $out/bin/hello
"""
# ran in a separate derivation which has hello package in builtInputs
# converts to checks.package-hello in flake.nix
checkCommand = """
  hello | grep
"""
