#v5:
#  - same as v3 but
#  - we can define per package options which can be used in bash sections


description = "A description of a flake"
maintainers = [
  "Eelco Dolstra <edolstra@gmail.com>",
]

[config]
binary-caches = [
  "https://my-cache.example.org",
]

[inputs]
nixpkgs = "20.03"
dwarffs = "master"

[[package]]
version = "1.2.0"
src = "./."
platforms = [
  "x86_64-linux",
  "aarch64-macos",
]
dependencies = [
  "nixpkgs#cowsay",
  "nixpkgs#bash",
  "dwarffs",
]
buildPhase = """
  echo "Building hello.sh ..."
  cat > hello <<EOF
  #!$(realpath bash)
  DEFAULT="{{options.who}}"
  exec $(realpath cowsay) Hello ${1:-DEFAULT}
  EOF
  chmod +x hello
"""
installPhase = """
  mkdir -p $out/bin
  cp ./hello $out/bin/hello
"""
# ran in a separate derivation which has hello package in builtInputs
# converts to checks.package-hello in flake.nix
checkCommand = """
  hello | grep
"""

  # this options will belong to the to the nearest [[package]]
  [package.options.who]
  description = "Who we're saying hello to."
  type = "string"
  default = "World"
