# v1:
#  - only include "metadata" of flake.nix
#  - this would make command like `nix config set` possible
#  - outputs are still provided by flake.nix, eg.:
#    { self, nixpkgs }:
#    {
#      ...
#    }

maintainers = [ "Eelco Dolstra <edolstra@gmail.com>" ]
description = "A description of a flake"

[config]
binaryCaches = [ "https://my-cache.example.org" ]

[inputs]
nixpkgs = "20.03"
dwarffs = "master"
