# flake metadata
maintainers = [ "Name Surname <name.surname@example.com>" ]
description = "A program that prints a friendly greeting"

[hello] # name of the module
extends = ["package", "stdenv"] # modules that it extends
pname = "hello" # set an option declared by the 'package' module
version = "1.12" # idem
environment.WHO = "World" # set an option declared by the 'derivation' module
buildCommand = """ # idem
  mkdir -p $out/bin
  cat > $out/bin/hello <<EOF
  #! /bin/sh
  echo Hello $WHO
  EOF
  chmod +x $out/bin/hello
"""

[my-hello]
extends = ["hello", "bundle"]
environment.WHO = "Utrecht"
