description = "My own Hello World"
maintainers = [ "Eelco Dolstra <edolstra@gmail.com>" ]

[inputs]
hello.url = "github:tweag/nix-ux?dir=hello"

[my-hello]
extends = [ "hello#hello" ]
doc = '''
  A specialized version of the Hello package!
'''
who = "NixCon"
